apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- device-plugin.yaml

images:
- name: device-plugin
  newName: quay.io/yshnaidm/simple-device-plugin
  newTag: latest

configMapGenerator:
- files:
  - device_plugin_config.yaml
  name: device-plugin-config
